# Generated by Django 4.2 on 2024-04-29 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0002_user_groups_user_user_permissions"),
        ("profiles", "0002_remove_profile_id_alter_profile_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreferences",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="notification_preferences",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("meal_recommendation", models.BooleanField(default=True)),
                ("water_intake_reminder", models.BooleanField(default=True)),
                ("food_log_reminder", models.BooleanField(default=True)),
                ("goal_reminder", models.BooleanField(default=True)),
                ("healthy_eating_reminder", models.BooleanField(default=True)),
            ],
        ),
    ]
