# Generated by Django 4.2 on 2024-05-01 07:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_date_waterintake_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="waterintake",
            name="date",
        ),
        migrations.RemoveField(
            model_name="waterintake",
            name="user",
        ),
        migrations.DeleteModel(
            name="Date",
        ),
        migrations.DeleteModel(
            name="WaterIntake",
        ),
    ]
