# Generated by Django 4.2 on 2024-07-31 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_ot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OT',
        ),
    ]
