# Generated by Django 4.2 on 2024-05-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_diaries", "0002_exercise_exercise_unique_user_date_exercise"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="exercise",
            name="unique_user_date_exercise",
        ),
        migrations.AddConstraint(
            model_name="exercise",
            constraint=models.UniqueConstraint(
                fields=("user", "date", "name"), name="unique_user_date_name_exercise"
            ),
        ),
    ]
