# Generated by Django 4.2 on 2024-05-01 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("food_diaries", "0004_alter_exercise_user_alter_waterintake_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("servings", models.IntegerField()),
                ("energy", models.DecimalField(decimal_places=2, max_digits=5)),
                ("carbs", models.DecimalField(decimal_places=2, max_digits=5)),
                ("protein", models.DecimalField(decimal_places=2, max_digits=5)),
                ("fats", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_diaries.date",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="meal",
            constraint=models.UniqueConstraint(
                fields=("user", "date", "name"), name="unique_user_date_name_meal"
            ),
        ),
    ]
