# Generated by Django 4.2 on 2024-05-01 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("food_diaries", "0005_meal_meal_unique_user_date_name_meal"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnergyRequired",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("energy", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_diaries.date",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="energyrequired",
            constraint=models.UniqueConstraint(
                fields=("user", "date"), name="unique_user_date_energyrequired"
            ),
        ),
    ]
