# Generated by Django 4.2 on 2024-05-03 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("food_diaries", "0006_energyrequired_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaloryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calory", models.DecimalField(decimal_places=2, max_digits=8)),
                ("carbs", models.DecimalField(decimal_places=2, max_digits=5)),
                ("protein", models.DecimalField(decimal_places=2, max_digits=5)),
                ("fats", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_diaries.date",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="EnergyRequired",
        ),
        migrations.AddConstraint(
            model_name="calorylog",
            constraint=models.UniqueConstraint(
                fields=("user", "date", "calory"),
                name="unique_user_date_calory_calorylog",
            ),
        ),
    ]
