# Generated by Django 4.2 on 2024-05-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_diaries", "0008_rename_calorylog_calorielog"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="calorielog",
            name="unique_user_date_calory_calorylog",
        ),
        migrations.RenameField(
            model_name="calorielog",
            old_name="calory",
            new_name="calorie",
        ),
        migrations.AddConstraint(
            model_name="calorielog",
            constraint=models.UniqueConstraint(
                fields=("user", "date", "calorie"),
                name="unique_user_date_calorie_calorielog",
            ),
        ),
    ]
