# Generated by Django 4.2 on 2024-05-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "food_diaries",
            "0009_remove_calorielog_unique_user_date_calory_calorylog_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
