# Generated by Django 4.2 on 2024-06-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_diaries', '0010_meal_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='energy_per_minute',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5),
            preserve_default=False,
        ),
    ]
