# Generated by Django 4.2 on 2024-06-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_diaries', '0011_exercise_energy_per_minute'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exercise',
            name='unique_user_date_name_exercise',
        ),
        migrations.RemoveConstraint(
            model_name='waterintake',
            name='unique_user_date_waterintake',
        ),
        migrations.AddConstraint(
            model_name='waterintake',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_user_date_water_intake'),
        ),
    ]
