# Generated by Django 4.2 on 2024-07-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_diaries', '0013_alter_calorielog_calorie_alter_calorielog_carbs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image_url',
            field=models.URLField(blank=True, max_length=2500, null=True),
        ),
    ]
