# Generated by Django 4.2 on 2024-07-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_diaries', '0014_alter_meal_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image_url',
            field=models.URLField(blank=True, max_length=3000, null=True),
        ),
    ]
